### ISSUE TITLE
TeaVM has newer versions available

### ISSUE THREAD

**Issue by ScraM-Team** [renatoathaydes/jvm-alternatives-to-js#1]
Thank you for comparing these frameworks.  It is good to see some concrete, objective measurements.  These tools are very helpful for Java/JVM developers, as well as anyone wanting a unified, mature toolchain for the web.

Would it be possible to test a newer version of TeaVM?  The version you used (0.5.1) is over a year old.  Newer versions are available on bintray here:

https://bintray.com/konsoletyper/teavm/teavm-dev

Details on the maven setup are in the README under "Preview builds":

https://github.com/konsoletyper/teavm/blob/master/README.md

Thanks...

**Comment by renatoathaydes** [comment]
I've used the latest stable release available. As I understand it, TeaVM is being very slow on releases - on the order of one release in 2 years... so the fact that I used an old version of TeaVM is not my fault, but reflects the very slow release cycle... with that said, it would be nice to test the dev version... can't you check out the project and try to upgrade the version?

**Comment by ScraM-Team** [comment]
I created a PR for the latest version of TeaVM.  It is substantially improved.  I'm seeing 17% better FCP and 56% better code size.  If you see the same results could you please update the charts in your blog post?  I think it paints a more realistic picture for TeaVM and puts it on much closer footing with JSweet,

**Comment by renatoathaydes** [comment]
PR merged... thanks.

Here's the results I got:

![network-teavm-0 6 0-dev-723](https://user-images.githubusercontent.com/1901277/56824158-f8f7a980-6855-11e9-9a73-048e38f720da.png)

![lighthouse-teavm-0 6 0-dev-723](https://user-images.githubusercontent.com/1901277/56824164-fb5a0380-6855-11e9-8b17-714402a44918.png)

**Comment by ScraM-Team** [comment]
Great, that is the same improvement I saw: 0.2s better FCP score, and just 25KB of JavaScript to download.

Thanks for re-running the tests.  I think this really shows what TeaVM can do.
